### ISSUE TITLE
Contribute: Todo-List

### ISSUE THREAD

**Issue by toby63** [mumble-voip/mumble-www#133]
Because some things might need to be changed in the future, I will collect all ideas and tasks here:

- [ ] General: edit and exchange links to the wiki with links to the new documentation (once it's implemented) (see also: #35 and #125)
    - [ ] [Documentation] also edit the section about "documentation" once the new documentation is in place
- [ ] [Development -> Coding] Add label for important issues
- [ ] [Documentation] Add label for documentation pull requests 
- [ ] [Coding] Add link to **C++ guidelines & tools** once it's ready, see [Discussion - C++ guidelines & tools](https://github.com/mumble-voip/mumble/discussions/4261)
- [ ] Add a Donate Section? (I think it might not fit into the contribution section.) (see also: #54)
     - Alternative would be a seperate Donate page
- [ ] [Hosting] Add (a new) list of hosters?

**Comment by Kissaki** [comment]
I’m confused. Are these personal notes for yourself??

**Comment by Kissaki** [comment]
This ticket is not actionable and very broad/unspecific. Thus I am closing it.

If you feel like there needs some tracking for these, feel free to suggest a milestone or individual or planning approach. But atm I think this ticket is not solvable as-is and only contributes to ticket list explosion and complexity, making it harder to manage the others.

As for fixing the links is a part of the wiki move.

**Comment by toby63** [comment]
Well if you don't want this, I will certainly not remind anyone if such a list is even denied...

**Comment by Kissaki** [comment]
@Krzmbrzl what do you think about a list like this?

I don’t think this is the right format. Tickets and a project board would be preferable, or a different planning format (document). And I don't think we should refer and depend on other states of other projects too much, as that will simply be missed. It should either be linked explicitly, or mentioned in the task that initially introduces changes, that followup changes are necessary.

**Comment by toby63** [comment]
Well you also deleted my comments in the page files themselves.
If you have a different format, then we can use that.
But if we don't keep track of things, they will be forgotten anyway.

> And I don't think we should refer and depend on other states of other projects too much, as that will simply be missed. 

Potentially yes, but:
1. there is nothing against mentioning it in other tasks/PRs etc.
2. I think the website is often maintained by other people than the core project (at least regarding contributors), so this would be a hint for people what needs to be done to the website.

> It should either be linked explicitly, 

It is, whenever possible.

> or mentioned in the task that initially introduces changes, that followup changes are necessary.

The PR is merged, so that is not a good place.

**Comment by Kissaki** [comment]
> Well you also deleted my comments in the page files themselves.

I don’t know what you are referring to here.

**Comment by toby63** [comment]
>>  Well you also deleted my comments in the page files themselves.

> I don’t know what you are referring to here.

https://github.com/mumble-voip/mumble-www/commit/e5065e9a9b4cf7a404b3f56f8f793ae3537f526d

**Comment by Krzmbrzl** [comment]
> Krzmbrzl what do you think about a list like this?

Individual issues that are collected and managed on a project board would probably be better. However I am not sure if creating all these is actually worth the effort, so I was also not really bothered by this issue :shrug:

**Comment by Kissaki** [comment]
> > > Well you also deleted my comments in the page files themselves.
> 
> > I don’t know what you are referring to here.
> 
> [e5065e9](https://github.com/mumble-voip/mumble-www/commit/e5065e9a9b4cf7a404b3f56f8f793ae3537f526d)

If added in there they should be comments that will not be rendered in the frontend. Those html comments were sent out and rendered to clients as dead weight.

I don’t think a question is a good or useful comment in content sources. If it is still an open question it should be a topic/ticket up for discussion. And I have seen it elsewhere before like that, so I saw no reason why it should be in the content source. If the discussion leads to a decision to add something like that, that will be a task. If it does not, it concludes there. A comment like that can easily become stale and forgotten, outdated, and misleading or result in additional work or confusion as the discussion or conclusion elsewhere is not mentioned.

I really do not see what the second comment adds either. It seems like it is a change description, which should be in the commit description, instead of replacing content with it.

**Comment by toby63** [comment]
It doesn't matter now, it was just another example of where things should not be placed etc. in your oppinion.

**Comment by Kissaki** [comment]
I’ll reopen it as it seems helpful to you, and you want to track work with it.

**Comment by toby63** [comment]
Thx, I appreciate that :+1:.

**Comment by Kissaki** [comment]
Closing because this was supposedly a personal note/todo list, but assignment was removed.

The wiki was purged, so those points are outdated. The label points aren to clear to me. The other seem to be random/various ideas.
